---
title: "SRTR Dashboard"

output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: columns
    vertical_layout: fill
    include:
      after_body: footer.html
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(purrr)
library(DT)
library(plotly)
library(readxl)
library(haven)
library(ggplot2)
library(zipcodeR)
library(ggmap)
library(leaflet)
library(kableExtra)
library(crosstalk)
library(gtsummary)
# reset_gtsummary_theme()
# theme_gtsummary_journal(journal="jama")
# theme_gtsummary_compact()

#------------------ Parameters ------------------
# Set colors
# https://www.w3.org/TR/css-color-3/#svg-color
color1 = "purple"
color2 = RColorBrewer::brewer.pal(9, "PuRd")[7]
color3  = "#1f77b4"
color4 = "forestgreen"
color5 = "#660708"
color6 = "red"
color7 = "#ba181b"
color8 = "#e5383b"
color9 = "#FDBBBC"

suffix = list("age","gender","demographics", "blood_type")

for (i in suffix){
  data_path = "./data/old_data/"   # path to the data
  files = dir(data_path, 
              pattern = paste0("csrs_final_tables_2006_[A-Z][A-Z]_", i,".csv"))
  assign(paste0("df_all_", i),
         files %>%
           map(~ read_csv(file.path(data_path, .))%>%
                 mutate(org = str_replace(org, "HR", "Heart"),
                        org = str_replace(org, "HL", "Heart-Lung"),
                        org = str_replace(org, "IN", "Intestine"),
                        org = str_replace(org, "KI", "Kidney"),
                        org = str_replace(org, "KP", "Kidney-Pancreas"),
                        org = str_replace(org, "LI", "Liver"),
                        org = str_replace(org, "LU", "Lung"),
                        org = str_replace(org, "PA", "Pancreas"))) %>%
           reduce(rbind))
  }

organ_race = df_all_demographics %>% distinct(org) %>% pull()
organ_age = df_all_age %>% distinct(org) %>% pull()
organ_gender = df_all_gender %>% distinct(org) %>% pull()
organ_blood_type = df_all_blood_type %>% distinct(org) %>% pull()

no_transplant_centers = 
  df_all_demographics %>% 
  distinct(entire_name) %>% 
  count() %>% 
  pull()

avg_asian = 
  df_all_demographics %>% 
  filter(race_category == 'asian_allc2') %>% 
  select(race_category_percent)%>% 
  pull() %>%
  mean(na.rm = TRUE) %>%
  round(.,1)

avg_black = 
  df_all_demographics %>% 
  filter(race_category == 'african_american_allc2') %>% 
  select(race_category_percent)%>% 
  pull() %>%
  mean(na.rm = TRUE) %>%
  round(.,1)

avg_latino = 
  df_all_demographics %>% 
  filter(race_category == 'hispanic_latino_allc2') %>% 
  select(race_category_percent)%>% 
  pull() %>%
  mean(na.rm = TRUE) %>%
  round(.,1)

avg_white = 
  df_all_demographics %>% 
  filter(race_category == 'white_allc2') %>% 
  select(race_category_percent)%>% 
  pull() %>%
  mean(na.rm = TRUE) %>%
  round(.,1)

avg_other = 
  df_all_demographics %>% 
  filter(race_category == 'race_other_allc2') %>% 
  select(race_category_percent)%>% 
  pull() %>%
  mean(na.rm = TRUE) %>%
  round(.,1)

avg_unknown = 
  df_all_demographics %>% 
  filter(race_category == 'race_unknown_allc2') %>% 
  select(race_category_percent)%>% 
  pull() %>%
  mean(na.rm = TRUE) %>%
  round(.,1)

avg_unknown_other = 100 - sum(avg_asian, avg_black, avg_latino, avg_white)
  # df_all_demographics %>% 
  # filter(race_category == 'race_unknown_allc2' | race_category == 'race_other_allc2') %>% 
  # select(race_category_percent)%>% 
  # pull() %>%
  # mean(na.rm = TRUE) %>%
  # round(.,1)

df_one = 
  read_excel("./data/old_data/csrs_final_tables_2006_KI.xls", sheet = "Table B1") %>%
  janitor::clean_names() %>%
  drop_na()

# Here we read in, tidy, and merge with the zipcode file.
df_zipcodes = 
  read_excel("./data/old_data/zipcodes.xlsx", col_types = c("text", "numeric"), skip = 1) %>%
  janitor::clean_names()

# Now we cross reference the coordinates that correspond with each zipcode. 
for (zipcode in df_zipcodes["zipcode"]){
    df_zip_geo = tibble(geocode_zip(zipcode))
}

df_one_merge = 
  merge(df_zipcodes, df_zip_geo, all = TRUE) %>%
  merge(., df_one, all = TRUE)
```

Summary Statistics {data-icon="ion-stats-bars"}
=======================================================================

Column { data-width=175 }
-----------------------------------------------------------------------

### Transplant Centers {.value-box}
```{r}
valueBox(value = paste(format(no_transplant_centers, big.mark = ","), "", sep = " "), 
         caption = "Total transplant centers", 
         icon = "fas fa-hospital", 
         color = color1)
```

### Number of Recipients {.value-box}
```{r}
valueBox(value = paste(format(avg_unknown, big.mark = ","), "", sep = " "), 
         caption = "Number of transplant recipients", 
         icon = "fas fa-users", 
         color = color2)
```

### Percent Asian {.value-box}
```{r}
valueBox(value = paste(format(avg_asian, big.mark = ","), "%", sep = " "), 
         caption = paste0("Percent of recipients who identify as",'<br>',"Asian/Pacific Islander"), 
         icon = "fas fa-procedures", 
         color = color3)
```

### Percent Black {.value-box}
```{r}
valueBox(value = paste(format(avg_black, big.mark = ","), "%", sep = " "), 
         caption = paste0("Percent of recipients who identify as",'<br>',"Black/African American"), 
         icon = "fas fa-procedures", 
         color = color4)
```

### Percent Latino {.value-box}
```{r}
valueBox(value = paste(format(avg_latino, big.mark = ","), "%", sep = " "), 
         caption = paste0("Percent of recipients who identify as",'<br>',"Latinx/Hispanic"), 
         icon = "fas fa-procedures", 
         color = color6)
```

### Percent White {.value-box}
```{r}
valueBox(value = paste(format(avg_white, big.mark = ","), "%", sep = " "), 
         caption = paste0("Percent of recipients who identify as",'<br>',"White/Caucasian"), 
         icon = "fas fa-procedures", 
         color = color9)
```

### Percent Other {.value-box}
```{r}
valueBox(value = paste(format(avg_other, big.mark = ","), "%", sep = " "), 
         caption = "Percent of recipients of other race/ethnicity", 
         icon = "fas fa-procedures", 
         color = "yellow")
```

Column {.tabset}
-----------------------------------------------------------------------

### Tab 1 
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_a = 
  df_all_demographics %>%
    rename(Race = race_category_percent, Zipcode = zipcode) %>%
    mutate(race_category =
             str_replace(race_category, "african_american_allc2", "African American"),
           race_category =
             str_replace(race_category, "asian_allc2", "Asian"),
           race_category =
             str_replace(race_category, "hispanic_latino_allc2", "Hispanic or Latino"),
           race_category =
             str_replace(race_category, "race_other_allc2", "Other"),
           race_category = str_replace(race_category, "race_unknown_allc2", "Unknown"),
           race_category = str_replace(race_category, "white_allc2", "White")) %>%
    # filter(organ_race == input$organ_race) %>%
    plot_ly(x = ~Zipcode, y = ~Race, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~race_category, colors = "viridis")
fig_a  %>% 
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Race/Ethnicity'),
         legend = list(title=list(text='<b> Race/Ethnicity </b>')))

```
</div>
<div>
```{r}
fig_b = 
  df_all_age  %>%
    mutate(
      age_category = str_replace(age_category, "age_2_allc2", "Less Than 2 Years"),
      age_category = str_replace(age_category, "age_2_11_allc2", "2 to 11 Years"),
      age_category = str_replace(age_category, "age_12_17_allc2", "12 to 17 Years"),
      age_category = str_replace(age_category, "age_18_34_allc2", "18 to 34 Years"),
      age_category = str_replace(age_category,"age_35_49_allc2", "35 to 49 Years"),
      age_category = str_replace(age_category, "age_50_64_allc2", "50 to 64 Years"),
      age_category = str_replace(age_category, "age_65_69_allc2", "65 to 69 Years"),
      age_category = str_replace (age_category, "age_70_allc2", "More Than 70 Years"),
      age_category = factor(age_category, 
                            levels = c("Less Than 2 Years","2 to 11 Years",
                                       "12 to 17 Years", "18 to 34 Years", 
                                       "35 to 49 Years", "50 to 64 Years",
                                       "65 to 69 Years", "More Than 70 Years"))) %>%
    rename(Age_Group = age_category_percent, Zipcode = zipcode) %>%
    # filter(organ_age == input$organ_age) %>%
    plot_ly(x = ~Zipcode, y = ~Age_Group, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~age_category, colors = "viridis")
fig_b %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Age Group'),
         legend = list(title=list(text='<b> Age Group </b>')))
```
</div>
</div>
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_c = 
  df_all_gender %>%
    rename(Gender = gender_category_percent, Zipcode = zipcode) %>%
    mutate(gender_category = str_replace(gender_category, "female_allc2", "Female"),
           gender_category = str_replace(gender_category, "male_allc2", "Male")) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~Gender, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~gender_category, colors = "viridis")
fig_c %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Gender'),
         legend = list(title=list(text='<b> Gender </b>')))
```
</div>
<div>
```{r}
fig_d = 
  df_all_blood_type %>%
    rename("Blood Type" = blood_type_category_percent, Zipcode = zipcode) %>%
    mutate(blood_type_category = 
             str_replace(blood_type_category, "blood_type_a_allc2", "A"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_b_allc2", "B"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_o_allc2", "O"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_ab_allc2", "AB"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_unknown_allc2", "Unknown"),
           blood_type_category = 
             factor(blood_type_category, levels = c("A","B","O", "AB","Unknown"))) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~`Blood Type`, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~blood_type_category, colors = "viridis")
fig_d %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Blood Type'),
         legend = list(title=list(text='<b> Blood Type </b>')))
```
</div>
</div>
### Tab 2
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_a = 
  df_all_demographics %>%
    rename(Race = race_category_percent, Zipcode = zipcode) %>%
    mutate(race_category =
             str_replace(race_category, "african_american_allc2", "African American"),
           race_category =
             str_replace(race_category, "asian_allc2", "Asian"),
           race_category =
             str_replace(race_category, "hispanic_latino_allc2", "Hispanic or Latino"),
           race_category =
             str_replace(race_category, "race_other_allc2", "Other"),
           race_category = str_replace(race_category, "race_unknown_allc2", "Unknown"),
           race_category = str_replace(race_category, "white_allc2", "White")) %>%
    # filter(organ_race == input$organ_race) %>%
    plot_ly(x = ~Zipcode, y = ~Race, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~race_category, colors = "viridis")
fig_a  %>% 
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Race/Ethnicity'),
         legend = list(title=list(text='<b> Race/Ethnicity </b>')))

```
</div>
<div>
```{r}
fig_b = 
  df_all_age  %>%
    mutate(
      age_category = str_replace(age_category, "age_2_allc2", "Less Than 2 Years"),
      age_category = str_replace(age_category, "age_2_11_allc2", "2 to 11 Years"),
      age_category = str_replace(age_category, "age_12_17_allc2", "12 to 17 Years"),
      age_category = str_replace(age_category, "age_18_34_allc2", "18 to 34 Years"),
      age_category = str_replace(age_category,"age_35_49_allc2", "35 to 49 Years"),
      age_category = str_replace(age_category, "age_50_64_allc2", "50 to 64 Years"),
      age_category = str_replace(age_category, "age_65_69_allc2", "65 to 69 Years"),
      age_category = str_replace (age_category, "age_70_allc2", "More Than 70 Years"),
      age_category = factor(age_category, 
                            levels = c("Less Than 2 Years","2 to 11 Years",
                                       "12 to 17 Years", "18 to 34 Years", 
                                       "35 to 49 Years", "50 to 64 Years",
                                       "65 to 69 Years", "More Than 70 Years"))) %>%
    rename(Age_Group = age_category_percent, Zipcode = zipcode) %>%
    # filter(organ_age == input$organ_age) %>%
    plot_ly(x = ~Zipcode, y = ~Age_Group, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~age_category, colors = "viridis")
fig_b %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Age Group'),
         legend = list(title=list(text='<b> Age Group </b>')))
```
</div>
</div>
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_c = 
  df_all_gender %>%
    rename(Gender = gender_category_percent, Zipcode = zipcode) %>%
    mutate(gender_category = str_replace(gender_category, "female_allc2", "Female"),
           gender_category = str_replace(gender_category, "male_allc2", "Male")) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~Gender, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~gender_category, colors = "viridis")
fig_c %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Gender'),
         legend = list(title=list(text='<b> Gender </b>')))
```
</div>
<div>
```{r}
fig_d = 
  df_all_blood_type %>%
    rename("Blood Type" = blood_type_category_percent, Zipcode = zipcode) %>%
    mutate(blood_type_category = 
             str_replace(blood_type_category, "blood_type_a_allc2", "A"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_b_allc2", "B"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_o_allc2", "O"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_ab_allc2", "AB"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_unknown_allc2", "Unknown"),
           blood_type_category = 
             factor(blood_type_category, levels = c("A","B","O", "AB","Unknown"))) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~`Blood Type`, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~blood_type_category, colors = "viridis")
fig_d %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Blood Type'),
         legend = list(title=list(text='<b> Blood Type </b>')))
```
</div>
</div>

### Tab 3 

<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_a = 
  df_all_demographics %>%
    rename(Race = race_category_percent, Zipcode = zipcode) %>%
    mutate(race_category =
             str_replace(race_category, "african_american_allc2", "African American"),
           race_category =
             str_replace(race_category, "asian_allc2", "Asian"),
           race_category =
             str_replace(race_category, "hispanic_latino_allc2", "Hispanic or Latino"),
           race_category =
             str_replace(race_category, "race_other_allc2", "Other"),
           race_category = str_replace(race_category, "race_unknown_allc2", "Unknown"),
           race_category = str_replace(race_category, "white_allc2", "White")) %>%
    # filter(organ_race == input$organ_race) %>%
    plot_ly(x = ~Zipcode, y = ~Race, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~race_category, colors = "viridis")
fig_a  %>% 
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Race/Ethnicity'),
         legend = list(title=list(text='<b> Race/Ethnicity </b>')))

```
</div>
<div>
```{r}
fig_b = 
  df_all_age  %>%
    mutate(
      age_category = str_replace(age_category, "age_2_allc2", "Less Than 2 Years"),
      age_category = str_replace(age_category, "age_2_11_allc2", "2 to 11 Years"),
      age_category = str_replace(age_category, "age_12_17_allc2", "12 to 17 Years"),
      age_category = str_replace(age_category, "age_18_34_allc2", "18 to 34 Years"),
      age_category = str_replace(age_category,"age_35_49_allc2", "35 to 49 Years"),
      age_category = str_replace(age_category, "age_50_64_allc2", "50 to 64 Years"),
      age_category = str_replace(age_category, "age_65_69_allc2", "65 to 69 Years"),
      age_category = str_replace (age_category, "age_70_allc2", "More Than 70 Years"),
      age_category = factor(age_category, 
                            levels = c("Less Than 2 Years","2 to 11 Years",
                                       "12 to 17 Years", "18 to 34 Years", 
                                       "35 to 49 Years", "50 to 64 Years",
                                       "65 to 69 Years", "More Than 70 Years"))) %>%
    rename(Age_Group = age_category_percent, Zipcode = zipcode) %>%
    # filter(organ_age == input$organ_age) %>%
    plot_ly(x = ~Zipcode, y = ~Age_Group, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~age_category, colors = "viridis")
fig_b %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Age Group'),
         legend = list(title=list(text='<b> Age Group </b>')))
```
</div>
</div>
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_c = 
  df_all_gender %>%
    rename(Gender = gender_category_percent, Zipcode = zipcode) %>%
    mutate(gender_category = str_replace(gender_category, "female_allc2", "Female"),
           gender_category = str_replace(gender_category, "male_allc2", "Male")) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~Gender, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~gender_category, colors = "viridis")
fig_c %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Gender'),
         legend = list(title=list(text='<b> Gender </b>')))
```
</div>
<div>
```{r}
fig_d = 
  df_all_blood_type %>%
    rename("Blood Type" = blood_type_category_percent, Zipcode = zipcode) %>%
    mutate(blood_type_category = 
             str_replace(blood_type_category, "blood_type_a_allc2", "A"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_b_allc2", "B"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_o_allc2", "O"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_ab_allc2", "AB"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_unknown_allc2", "Unknown"),
           blood_type_category = 
             factor(blood_type_category, levels = c("A","B","O", "AB","Unknown"))) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~`Blood Type`, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~blood_type_category, colors = "viridis")
fig_d %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Blood Type'),
         legend = list(title=list(text='<b> Blood Type </b>')))
```
</div>
</div>
### Tab 4 

<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_a = 
  df_all_demographics %>%
    rename(Race = race_category_percent, Zipcode = zipcode) %>%
    mutate(race_category =
             str_replace(race_category, "african_american_allc2", "African American"),
           race_category =
             str_replace(race_category, "asian_allc2", "Asian"),
           race_category =
             str_replace(race_category, "hispanic_latino_allc2", "Hispanic or Latino"),
           race_category =
             str_replace(race_category, "race_other_allc2", "Other"),
           race_category = str_replace(race_category, "race_unknown_allc2", "Unknown"),
           race_category = str_replace(race_category, "white_allc2", "White")) %>%
    # filter(organ_race == input$organ_race) %>%
    plot_ly(x = ~Zipcode, y = ~Race, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~race_category, colors = "viridis")
fig_a  %>% 
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Race/Ethnicity'),
         legend = list(title=list(text='<b> Race/Ethnicity </b>')))

```
</div>
<div>
```{r}
fig_b = 
  df_all_age  %>%
    mutate(
      age_category = str_replace(age_category, "age_2_allc2", "Less Than 2 Years"),
      age_category = str_replace(age_category, "age_2_11_allc2", "2 to 11 Years"),
      age_category = str_replace(age_category, "age_12_17_allc2", "12 to 17 Years"),
      age_category = str_replace(age_category, "age_18_34_allc2", "18 to 34 Years"),
      age_category = str_replace(age_category,"age_35_49_allc2", "35 to 49 Years"),
      age_category = str_replace(age_category, "age_50_64_allc2", "50 to 64 Years"),
      age_category = str_replace(age_category, "age_65_69_allc2", "65 to 69 Years"),
      age_category = str_replace (age_category, "age_70_allc2", "More Than 70 Years"),
      age_category = factor(age_category, 
                            levels = c("Less Than 2 Years","2 to 11 Years",
                                       "12 to 17 Years", "18 to 34 Years", 
                                       "35 to 49 Years", "50 to 64 Years",
                                       "65 to 69 Years", "More Than 70 Years"))) %>%
    rename(Age_Group = age_category_percent, Zipcode = zipcode) %>%
    # filter(organ_age == input$organ_age) %>%
    plot_ly(x = ~Zipcode, y = ~Age_Group, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~age_category, colors = "viridis")
fig_b %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Age Group'),
         legend = list(title=list(text='<b> Age Group </b>')))
```
</div>
</div>
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_c = 
  df_all_gender %>%
    rename(Gender = gender_category_percent, Zipcode = zipcode) %>%
    mutate(gender_category = str_replace(gender_category, "female_allc2", "Female"),
           gender_category = str_replace(gender_category, "male_allc2", "Male")) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~Gender, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~gender_category, colors = "viridis")
fig_c %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Gender'),
         legend = list(title=list(text='<b> Gender </b>')))
```
</div>
<div>
```{r}
fig_d = 
  df_all_blood_type %>%
    rename("Blood Type" = blood_type_category_percent, Zipcode = zipcode) %>%
    mutate(blood_type_category = 
             str_replace(blood_type_category, "blood_type_a_allc2", "A"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_b_allc2", "B"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_o_allc2", "O"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_ab_allc2", "AB"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_unknown_allc2", "Unknown"),
           blood_type_category = 
             factor(blood_type_category, levels = c("A","B","O", "AB","Unknown"))) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~`Blood Type`, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~blood_type_category, colors = "viridis")
fig_d %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Blood Type'),
         legend = list(title=list(text='<b> Blood Type </b>')))
```
</div>
</div>

Patient Demographics {data-icon="ion-stats-bars"}
===================================== 
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_a = 
  df_all_demographics %>%
    rename(Race = race_category_percent, Zipcode = zipcode) %>%
    mutate(race_category =
             str_replace(race_category, "african_american_allc2", "African American"),
           race_category =
             str_replace(race_category, "asian_allc2", "Asian"),
           race_category =
             str_replace(race_category, "hispanic_latino_allc2", "Hispanic or Latino"),
           race_category =
             str_replace(race_category, "race_other_allc2", "Other"),
           race_category = str_replace(race_category, "race_unknown_allc2", "Unknown"),
           race_category = str_replace(race_category, "white_allc2", "White")) %>%
    # filter(organ_race == input$organ_race) %>%
    plot_ly(x = ~Zipcode, y = ~Race, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~race_category, colors = "viridis")
fig_a  %>% 
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Race/Ethnicity'),
         legend = list(title=list(text='<b> Race/Ethnicity </b>')))

```
</div>
<div>
```{r}
fig_b = 
  df_all_age  %>%
    mutate(
      age_category = str_replace(age_category, "age_2_allc2", "Less Than 2 Years"),
      age_category = str_replace(age_category, "age_2_11_allc2", "2 to 11 Years"),
      age_category = str_replace(age_category, "age_12_17_allc2", "12 to 17 Years"),
      age_category = str_replace(age_category, "age_18_34_allc2", "18 to 34 Years"),
      age_category = str_replace(age_category,"age_35_49_allc2", "35 to 49 Years"),
      age_category = str_replace(age_category, "age_50_64_allc2", "50 to 64 Years"),
      age_category = str_replace(age_category, "age_65_69_allc2", "65 to 69 Years"),
      age_category = str_replace (age_category, "age_70_allc2", "More Than 70 Years"),
      age_category = factor(age_category, 
                            levels = c("Less Than 2 Years","2 to 11 Years",
                                       "12 to 17 Years", "18 to 34 Years", 
                                       "35 to 49 Years", "50 to 64 Years",
                                       "65 to 69 Years", "More Than 70 Years"))) %>%
    rename(Age_Group = age_category_percent, Zipcode = zipcode) %>%
    # filter(organ_age == input$organ_age) %>%
    plot_ly(x = ~Zipcode, y = ~Age_Group, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~age_category, colors = "viridis")
fig_b %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Age Group'),
         legend = list(title=list(text='<b> Age Group </b>')))
```
</div>
</div>
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_c = 
  df_all_gender %>%
    rename(Gender = gender_category_percent, Zipcode = zipcode) %>%
    mutate(gender_category = str_replace(gender_category, "female_allc2", "Female"),
           gender_category = str_replace(gender_category, "male_allc2", "Male")) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~Gender, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~gender_category, colors = "viridis")
fig_c %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Gender'),
         legend = list(title=list(text='<b> Gender </b>')))
```
</div>
<div>
```{r}
fig_d = 
  df_all_blood_type %>%
    rename("Blood Type" = blood_type_category_percent, Zipcode = zipcode) %>%
    mutate(blood_type_category = 
             str_replace(blood_type_category, "blood_type_a_allc2", "A"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_b_allc2", "B"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_o_allc2", "O"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_ab_allc2", "AB"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_unknown_allc2", "Unknown"),
           blood_type_category = 
             factor(blood_type_category, levels = c("A","B","O", "AB","Unknown"))) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~`Blood Type`, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~blood_type_category, colors = "viridis")
fig_d %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Blood Type'),
         legend = list(title=list(text='<b> Blood Type </b>')))
```
</div>
</div>

Transplant Outcomes {data-icon="ion-stats-bars"}
=====================================  
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_a = 
  df_all_demographics %>%
    rename(Race = race_category_percent, Zipcode = zipcode) %>%
    mutate(race_category =
             str_replace(race_category, "african_american_allc2", "African American"),
           race_category =
             str_replace(race_category, "asian_allc2", "Asian"),
           race_category =
             str_replace(race_category, "hispanic_latino_allc2", "Hispanic or Latino"),
           race_category =
             str_replace(race_category, "race_other_allc2", "Other"),
           race_category = str_replace(race_category, "race_unknown_allc2", "Unknown"),
           race_category = str_replace(race_category, "white_allc2", "White")) %>%
    # filter(organ_race == input$organ_race) %>%
    plot_ly(x = ~Zipcode, y = ~Race, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~race_category, colors = "viridis")
fig_a  %>% 
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Race/Ethnicity'),
         legend = list(title=list(text='<b> Race/Ethnicity </b>')))

```
</div>
<div>
```{r}
fig_b = 
  df_all_age  %>%
    mutate(
      age_category = str_replace(age_category, "age_2_allc2", "Less Than 2 Years"),
      age_category = str_replace(age_category, "age_2_11_allc2", "2 to 11 Years"),
      age_category = str_replace(age_category, "age_12_17_allc2", "12 to 17 Years"),
      age_category = str_replace(age_category, "age_18_34_allc2", "18 to 34 Years"),
      age_category = str_replace(age_category,"age_35_49_allc2", "35 to 49 Years"),
      age_category = str_replace(age_category, "age_50_64_allc2", "50 to 64 Years"),
      age_category = str_replace(age_category, "age_65_69_allc2", "65 to 69 Years"),
      age_category = str_replace (age_category, "age_70_allc2", "More Than 70 Years"),
      age_category = factor(age_category, 
                            levels = c("Less Than 2 Years","2 to 11 Years",
                                       "12 to 17 Years", "18 to 34 Years", 
                                       "35 to 49 Years", "50 to 64 Years",
                                       "65 to 69 Years", "More Than 70 Years"))) %>%
    rename(Age_Group = age_category_percent, Zipcode = zipcode) %>%
    # filter(organ_age == input$organ_age) %>%
    plot_ly(x = ~Zipcode, y = ~Age_Group, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~age_category, colors = "viridis")
fig_b %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Age Group'),
         legend = list(title=list(text='<b> Age Group </b>')))
```
</div>
</div>
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_c = 
  df_all_gender %>%
    rename(Gender = gender_category_percent, Zipcode = zipcode) %>%
    mutate(gender_category = str_replace(gender_category, "female_allc2", "Female"),
           gender_category = str_replace(gender_category, "male_allc2", "Male")) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~Gender, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~gender_category, colors = "viridis")
fig_c %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Gender'),
         legend = list(title=list(text='<b> Gender </b>')))
```
</div>
<div>
```{r}
fig_d = 
  df_all_blood_type %>%
    rename("Blood Type" = blood_type_category_percent, Zipcode = zipcode) %>%
    mutate(blood_type_category = 
             str_replace(blood_type_category, "blood_type_a_allc2", "A"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_b_allc2", "B"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_o_allc2", "O"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_ab_allc2", "AB"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_unknown_allc2", "Unknown"),
           blood_type_category = 
             factor(blood_type_category, levels = c("A","B","O", "AB","Unknown"))) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~`Blood Type`, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~blood_type_category, colors = "viridis")
fig_d %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Blood Type'),
         legend = list(title=list(text='<b> Blood Type </b>')))
```
</div>
</div>

Organ Offer Acceptance Practices {data-icon="ion-stats-bars"}
=====================================  
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_a = 
  df_all_demographics %>%
    rename(Race = race_category_percent, Zipcode = zipcode) %>%
    mutate(race_category =
             str_replace(race_category, "african_american_allc2", "African American"),
           race_category =
             str_replace(race_category, "asian_allc2", "Asian"),
           race_category =
             str_replace(race_category, "hispanic_latino_allc2", "Hispanic or Latino"),
           race_category =
             str_replace(race_category, "race_other_allc2", "Other"),
           race_category = str_replace(race_category, "race_unknown_allc2", "Unknown"),
           race_category = str_replace(race_category, "white_allc2", "White")) %>%
    # filter(organ_race == input$organ_race) %>%
    plot_ly(x = ~Zipcode, y = ~Race, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~race_category, colors = "viridis")
fig_a  %>% 
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Race/Ethnicity'),
         legend = list(title=list(text='<b> Race/Ethnicity </b>')))

```
</div>
<div>
```{r}
fig_b = 
  df_all_age  %>%
    mutate(
      age_category = str_replace(age_category, "age_2_allc2", "Less Than 2 Years"),
      age_category = str_replace(age_category, "age_2_11_allc2", "2 to 11 Years"),
      age_category = str_replace(age_category, "age_12_17_allc2", "12 to 17 Years"),
      age_category = str_replace(age_category, "age_18_34_allc2", "18 to 34 Years"),
      age_category = str_replace(age_category,"age_35_49_allc2", "35 to 49 Years"),
      age_category = str_replace(age_category, "age_50_64_allc2", "50 to 64 Years"),
      age_category = str_replace(age_category, "age_65_69_allc2", "65 to 69 Years"),
      age_category = str_replace (age_category, "age_70_allc2", "More Than 70 Years"),
      age_category = factor(age_category, 
                            levels = c("Less Than 2 Years","2 to 11 Years",
                                       "12 to 17 Years", "18 to 34 Years", 
                                       "35 to 49 Years", "50 to 64 Years",
                                       "65 to 69 Years", "More Than 70 Years"))) %>%
    rename(Age_Group = age_category_percent, Zipcode = zipcode) %>%
    # filter(organ_age == input$organ_age) %>%
    plot_ly(x = ~Zipcode, y = ~Age_Group, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~age_category, colors = "viridis")
fig_b %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Age Group'),
         legend = list(title=list(text='<b> Age Group </b>')))
```
</div>
</div>
<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
<div>
```{r}
fig_c = 
  df_all_gender %>%
    rename(Gender = gender_category_percent, Zipcode = zipcode) %>%
    mutate(gender_category = str_replace(gender_category, "female_allc2", "Female"),
           gender_category = str_replace(gender_category, "male_allc2", "Male")) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~Gender, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~gender_category, colors = "viridis")
fig_c %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Gender'),
         legend = list(title=list(text='<b> Gender </b>')))
```
</div>
<div>
```{r}
fig_d = 
  df_all_blood_type %>%
    rename("Blood Type" = blood_type_category_percent, Zipcode = zipcode) %>%
    mutate(blood_type_category = 
             str_replace(blood_type_category, "blood_type_a_allc2", "A"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_b_allc2", "B"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_o_allc2", "O"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_ab_allc2", "AB"),
           blood_type_category = 
             str_replace(blood_type_category, "blood_type_unknown_allc2", "Unknown"),
           blood_type_category = 
             factor(blood_type_category, levels = c("A","B","O", "AB","Unknown"))) %>%
    # filter(organ_gender == input$organ_gender) %>%
    plot_ly(x = ~Zipcode, y = ~`Blood Type`, 
            type = "scatter", mode = "markers",
            alpha = 0.9, color = ~blood_type_category, colors = "viridis")
fig_d %>%  
  layout(autosize = F, width = 550, height = 400,
         xaxis = list(title = 'Zip Code'),
         yaxis = list(title = 'Blood Type'),
         legend = list(title=list(text='<b> Blood Type </b>')))
```
</div>
</div>

Interactive Map {data-icon="ion-stats-bars"}
=====================================  

```{r include=FALSE}
df =
  df_one_merge %>%
  select(zipcode, center_name, lng, lat) %>%
  drop_na() %>%
  distinct

# Wrap data frame in SharedData
sd <- SharedData$new(df)

```

Column { data-width=500 }
-------------------------------------

### Interactive map
    
```{r map}
sd %>% 
  leaflet::leaflet() %>%
  leaflet::addProviderTiles(providers$OpenStreetMap) %>% 
  leaflet::addAwesomeMarkers(
    popup = ~paste0(
      "", df$center_name, "",
      
      "",
      
      "",
      "",
      "",
      "",
      
      "",
      "",
      "",
      "",
      "",
      
      "",
      "",
      "",
      "",
      "",
      
      "",
      "",
      "",
      "",
      "",
      
      "",
      "",
      "",
      "",
      ""
    ),  # end popup()
    icon = awesomeIcons(
      library = "ion",
      icon = ifelse(
        test = str_detect(df$center_name, "NY"),
        yes = "ion-android-star-outline",
        no = "ion-android-radio-button-off"
      ),
      iconColor = "white",
      markerColor = ifelse(
        test = df$lng == "-74", 
        yes = "red",
        no = "blue"
      )
    )
  ) %>%   # end addAwesomeMarkers()
  leaflet::addMeasure()
```

Column  { data-width=500 }
-------------------------------------
### Filters

```{r filters}
filter_select(
  id = "center",
  label = "Center Name",
  sharedData = sd,
  group = ~center_name
  )

filter_select(
  id = "zipcode",
  label = "Zip Code",
  sharedData = sd,
  group = ~zipcode
  )

filter_slider(
    id = "zipradius",
    label = "Radius",
    sharedData = sd,
    column = ~zipcode,
    step = 1,
    round = TRUE,
    sep = "",
    ticks = FALSE,
    width = "30%")
    
filter_slider(
    id = "numx",
    label = "Number of X",
    sharedData = sd,
    column = ~zipcode,
    step = 1,
    round = TRUE,
    sep = "",
    ticks = FALSE,
    width = "30%"
  )
```

### Datatable

```{r datatable}

sd %>%
  DT::datatable(
    filter = "top",  # allows filtering on each column
    extensions = c(
      "Buttons",  # add download buttons, etc
      "Scroller"  # for scrolling down the rows rather than pagination
    ),
    rownames = FALSE,  # remove rownames
    style = "bootstrap",
    class = "compact",
    width = "100%",
    options = list(
      dom = "Blrtip",  # specify content (search box, etc)
      deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(
        list(
          visible = FALSE,
          targets = c(2, 3, 5:15)
        )
      ),
      buttons = list(
        I("colvis"),  # turn columns on and off
        'copy', 
        'print',
        list(extend = 'collection',
             buttons = c('csv', 'excel', 'pdf'),
             text = 'Download')
      )
    ),
    colnames = c(
      "Center Name" = "center_name",
      "Zip Code" = "zipcode",
      "Longitude" = "lng",
      "Latitude" = "lat"
    )
  )
```


