---
title: "SRTR Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(purrr)
## Loading required package: viridisLite
library(plotly)
library(shiny)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
suffix = list("age","gender","demographics")

for (i in suffix){
  data_path = "./data/"   # path to the data
  files = dir(data_path, 
              pattern = paste0("csrs_final_tables_2006_[A-Z][A-Z]_", i,".csv"))
  assign(paste0("df_all_", i),
         files %>%
           map(~ read_csv(file.path(data_path, .))%>%
                 mutate(org = str_replace(org, "HR", "Heart"),
                        org = str_replace(org, "HL", "Heart-Lung"),
                        org = str_replace(org, "IN", "Intestine"),
                        org = str_replace(org, "KI", "Kidney"),
                        org = str_replace(org, "KP", "Kidney-Pancreas"),
                        org = str_replace(org, "LI", "Liver"),
                        org = str_replace(org, "LU", "Lung"),
                        org = str_replace(org, "PA", "Pancreas"))) %>%
           reduce(rbind))
  }

organ_race = df_all_demographics %>% distinct(org) %>% pull()
organ_age = df_all_age %>% distinct(org) %>% pull()
organ_gender = df_all_gender %>% distinct(org) %>% pull()

# selectInput widget
selectInput(
  "organ_race", 
  label = h3("Select demographics organ"),
  choices = organ_race, selected = "Kidney")

# selectInput widget
selectInput(
  "organ_age", 
  label = h3("Select age organ"),
  choices = organ_gender, selected = "Kidney")

# selectInput widget
selectInput(
  "organ_gender", 
  label = h3("Select gender organ"),
  choices = organ_gender, selected = "Kidney")

# phrase = "SRTR Multiorgan Transplant Data, August 2020 Release"

# df_one_age = read.csv("./data/csrs_final_tables_2006_HL_age.csv") 
# df_two_age = read.csv("./data/csrs_final_tables_2006_HR_age.csv") 
# df_three_age = read.csv("./data/csrs_final_tables_2006_IN_age.csv")
# df_four_age = read.csv("./data/csrs_final_tables_2006_KI_age.csv")
# df_five_age = read.csv("./data/csrs_final_tables_2006_KP_age.csv")
# df_six_age = read.csv("./data/csrs_final_tables_2006_LI_age.csv")
# df_seven_age = read.csv("./data/csrs_final_tables_2006_LU_age.csv")
# df_eight_age = read.csv("./data/csrs_final_tables_2006_PA_age.csv")
# df_all_age = rbind(df_one_age, df_two_age, df_three_age, df_four_age, 
#                    df_five_age, df_six_age, df_seven_age, df_eight_age)
# 
# df_one_gender = read.csv("./data/csrs_final_tables_2006_HL_gender.csv") 
# df_two_gender = read.csv("./data/csrs_final_tables_2006_HR_gender.csv") 
# df_three_gender = read.csv("./data/csrs_final_tables_2006_IN_gender.csv")
# df_four_gender = read.csv("./data/csrs_final_tables_2006_KI_gender.csv")
# df_five_gender = read.csv("./data/csrs_final_tables_2006_KP_gender.csv")
# df_six_gender = read.csv("./data/csrs_final_tables_2006_LI_gender.csv")
# df_seven_gender = read.csv("./data/csrs_final_tables_2006_LU_gender.csv")
# df_eight_gender = read.csv("./data/csrs_final_tables_2006_PA_gender.csv")
# df_all_gender = rbind(df_one_gender, df_two_gender, df_three_gender, 
#                       df_four_gender, df_five_gender, df_six_gender, 
#                       df_seven_gender, df_eight_gender)
# 
# df_one_demographics = read.csv("./data/csrs_final_tables_2006_HL_demographics.csv") 
# df_two_demographics = read.csv("./data/csrs_final_tables_2006_HR_demographics.csv") 
# df_three_demographics = read.csv("./data/csrs_final_tables_2006_IN_demographics.csv")
# df_four_demographics = read.csv("./data/csrs_final_tables_2006_KI_demographics.csv")
# df_five_demographics = read.csv("./data/csrs_final_tables_2006_KP_demographics.csv")
# df_six_demographics = read.csv("./data/csrs_final_tables_2006_LI_demographics.csv")
# df_seven_demographics = read.csv("./data/csrs_final_tables_2006_LU_demographics.csv")
# df_eight_demographics = read.csv("./data/csrs_final_tables_2006_PA_demographics.csv")
# df_all_demographics = rbind(df_one_demographics, df_two_demographics, 
#                             df_three_demographics, df_four_demographics, 
#                             df_five_demographics, df_six_demographics, 
#                             df_seven_demographics, df_eight_demographics)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Race (Percent) by Zipcode

```{r}

# renderPrint({ 
#   input[["organ_race"]]
# })

renderPlotly({
  df_all_demographics %>%
    rename(Race = race_category_percent, Zipcode = zipcode) %>%
    mutate(race_category =
             str_replace(race_category, "african_american_allc2", "African American"),
           race_category =
             str_replace(race_category, "asian_allc2", "Asian"),
           race_category =
             str_replace(race_category, "hispanic_latino_allc2", "Hispanic or Latino"),
           race_category =
             str_replace(race_category, "race_other_allc2", "Other"),
           race_category = str_replace(race_category, "race_unknown_allc2", "Unknown"),
           race_category = str_replace(race_category, "white_allc2", "White")) %>%
    filter(organ_race == input$organ_race) %>%
  plot_ly(x = ~Zipcode, y = ~Race, type = "scatter", mode = "markers",
          alpha = 0.9, color = ~race_category)})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Age Group (Percent) by Zipcode

```{r}
# renderPrint({ 
#   input[["organ_age"]]
# })
renderPlotly({
  df_all_age  %>%
    mutate(
      age_category = str_replace(age_category, "age_2_allc2", "Less Than 2 Years"),
      age_category = str_replace(age_category, "age_2_11_allc2", "2 to 11 Years"),
      age_category = str_replace(age_category, "age_12_17_allc2", "12 to 17 Years"),
      age_category = str_replace(age_category, "age_18_34_allc2", "18 to 34 Years"),
      age_category = str_replace(age_category,"age_35_49_allc2", "35 to 49 Years"),
      age_category = str_replace(age_category, "age_50_64_allc2", "50 to 64 Years"),
      age_category = str_replace(age_category, "age_65_69_allc2", "65 to 69 Years"),
      age_category = str_replace (age_category, "age_70_allc2", "More Than 70 Years"),
      age_category = factor(age_category, levels
                            =c("Less Than 2 Years","2 to 11 Years","12 to 17 Years",
                               "18 to 34 Years", "35 to 49 Years", "50 to 64 Years",
                               "65 to 69 Years", "More Than 70 Years"))) %>%
    rename(Age_Group = age_category_percent, Zipcode = zipcode) %>%
    filter(organ_age == input$organ_age) %>%
    plot_ly(x = ~Zipcode, y = ~Age_Group, type = "scatter", mode = "markers",
            alpha = 0.9, color = ~age_category)})
```

### Gender (Percent) by Zipcode

```{r}
# renderPrint({ 
#   input[["organ_gender"]]
# })
renderPlotly({
  df_all_gender %>%
    rename(Gender = gender_category_percent, Zipcode = zipcode) %>%
    mutate(gender_category = str_replace(gender_category, "female_allc2", "Female"),
           gender_category = str_replace(gender_category, "male_allc2", "Male")) %>%
    filter(
    organ_gender == input$organ_gender) %>%
  plot_ly(x = ~Zipcode, y = ~Gender, type = "scatter", mode = "markers",
          alpha = 0.9, color = ~gender_category)})
```