---
title: "downloading_data"
output: github_document
---

```{r}
library(readxl)
library(rvest)
library(stringr)
library(tidyverse)
```

Creating list of date codes and URLs for the current data file and all archived files.

Dates and URLs came from inspecting this website:
https://www.srtr.org/reports/program-specific-reports/


```{r}
archive_dates = c("1207", "1301", "1307", "1401", "1406", "1412", "1506", "1512", "1606", "1701", "1707", "1711", "1808", "1811", "1905", "1911", "2006")

current_file_date = "2105"

current_file_url = "https://www.srtr.org/assets/media/PSRdownloads/csrs_tables/csrs_final_tables_2105_KI.xls"

url_base = "https://www.srtr.org/assets/media/PSRdownloads/csrs_tables_all/csrs_final_tables_"

vec_urls = str_c(url_base, archive_dates, "all.zip")

vec_dates = list(
  date = archive_dates,
  url = vec_urls
)
```

Downloading the most recent data:

```{r}
temp = tempfile()

download.file(current_file_url, temp, mode = "wb")

current_data = sapply(readxl::excel_sheets(temp), 
                    simplify = F, USE.NAMES = T,
            function(X) readxl::read_xls(temp, sheet = X))

unlink(temp)
```

Function to download archived files:

```{r}
download_archived_data = function(url) {
  temp = tempfile()
  
  download.file(url, temp, mode = "wb")
  
  ki_file = tibble(files = as.character(unzip(temp, list = TRUE)$Name)) %>% 
    filter(str_detect(files, "KI\\.[xX][lL][sS]$"))
  
  ki_filepath = ki_file[[1]]

  ki_data = sapply(readxl::excel_sheets(unzip(temp, ki_filepath)), 
                    simplify = F, USE.NAMES = T,
            function(X) readxl::read_xls(unzip(temp, ki_filepath), sheet = X))
  
  unlink(temp)
  unlink(ki_filepath)
  
  return(ki_data)
}
```

Compiling all data files (archived and current) into one nested list:

```{r}
data_all_yrs = map(.x = vec_dates$url, ~download_archived_data(url = .x))

data_all_yrs = append(data_all_yrs, list(current_data))

name_labels = vec_dates$date %>% 
  append(current_file_date)

names(data_all_yrs) = str_c("data_", name_labels)
```

Selecting only data of interest

```{r}

t1_function = function(df) {
  tbl1 = as_tibble(df[[1]]) %>% 
    select(1, CTR_CD, WLA_ADDCEN_NC2, WLA_ST_NC2, WLA_END_NC2, WLA_REMTXC_NC2, WLA_REMTXL_NC2, WLA_REMTXC_PCZ, WLA_REMTXL_PCZ, WLA_REMDIED_PCZ, WLA_REMDET_PCZ)
  tbl1
}

t2_function = function(df) {
  tbl2 = as_tibble(df[[2]]) %>% 
    select(1, CTR_CD, RELEASE_DATE, 
           WLC_A2_ALLC2, WLC_A10_ALLC2, WLC_A17_ALLC2, WLC_A34_ALLC2, WLC_A49_ALLC2, WLC_A64_ALLC2, WLC_GM_ALLC2, WLC_GF_ALLC2, WLC_RA_ALLC2, WLC_RB_ALLC2, WLC_RH_ALLC2, WLC_RO_ALLC2, WLC_RU_ALLC2, WLC_RW_ALLC2, WLC_PRA80_ALLC2, WLC_PTXY_ALLC2, WLC_KIDIA_ALLC2, WLC_KIGLO_ALLC2, WLC_KIHYP_ALLC2, WLC_KIMIS_ALLC2, WLC_KINEO_ALLC2, WLC_KIOTH_ALLC2, WLC_KIPOL_ALLC2, WLC_KIREN_ALLC2, WLC_KIRTR_ALLC2, WLC_KITUB_ALLC2, WLC_KICON_ALLC2)
  tbl2
}

t3_function = function(df) {
  if (length(df) <= 30) {tbl3 = as_tibble(df[[22]]) %>% 
    select(1, CTR_CD, RELEASE_DATE, TOC_SHR_C, TOC_WKDIALY_C)}
  else if (length(df) == 32) {tbl3 = as_tibble(df[[23]]) %>% 
    select(1, CTR_CD, RELEASE_DATE, TOC_SHR_C, TOC_WKDIALY_C)}
  else if (length(df) == 33) {tbl3 = as_tibble(df[[25]]) %>% 
    select(1, CTR_CD, RELEASE_DATE, TOC_SHR_C, TOC_WKDIALY_C)}
  else if (length(df) == 34) {tbl3 = as_tibble(df[[26]]) %>% 
    select(1, CTR_CD, RELEASE_DATE, TOC_SHR_C, TOC_WKDIALY_C)}
  tbl3
}

t4_function = function(df) {
  if (length(df) < 32) {tbl4 = as_tibble("")}
  if (length(df) == 32) {tbl4 = as_tibble(df[[16]]) %>% 
    select(1, CTR_CD, OA_OVERALL_HR_MN_CENTER, OA_LOWRISK_HR_MN_CENTER, OA_MEDIUMRISK_HR_MN_CENTER, OA_HIGHRISK_HR_MN_CENTER)}
  else if (length(df) == 33) {tbl4 = as_tibble(df[[18]]) %>% 
    select(1, CTR_CD, OA_OVERALL_HR_MN_CENTER, OA_LOWRISK_HR_MN_CENTER, OA_MEDIUMRISK_HR_MN_CENTER, OA_HIGHRISK_HR_MN_CENTER)}
  else if (length(df) == 34) {tbl4 = as_tibble(df[[19]]) %>% 
    select(1, CTR_CD, OA_OVERALL_HR_MN_CENTER, OA_LOWRISK_HR_MN_CENTER, OA_MEDIUMRISK_HR_MN_CENTER, OA_HIGHRISK_HR_MN_CENTER)}  
  tbl4 %>% mutate(RELEASE_DATE = df[[1]][[1, 4]])
  tbl4
}

wl_tx_counts = map(data_all_yrs, t1_function)
wl_demo = map(data_all_yrs, t2_function)
tx_out = map(data_all_yrs, t3_function)
ctr_oar = map(data_all_yrs, t4_function)

```
