---
title: "IterationMS"
author: "Matthew Spotnitz"
date: "11/24/2021"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
library(ggplot2)
library(zipcodeR)
library(ggmap)
library(leaflet)
library(kableExtra)
```
I will define the iterators
```{r}
path = "../data/csrs_final_tables_2006_KI.xls"
phrase = "STTR Kidney Transplant Data, August 2020 Release"
```
Function to read csv file
```{r}
read_file = function(x){
  x = read_excel(path, sheet = "Table B1")
x = janitor::clean_names(x)
str(x)
return(x) 
}
```
Function to clean dataframe
```{r}
clean_data_frame = function(x){
  x = x %>% rename(newlistings_center_time1 = wla_addcen_nc1, newlistings_center_time2 = wla_addcen_nc2, newlistings_center_all = wla_addcen_pcz,newlistings_regional = wla_addcen_prz, newlistings_usa = wla_addcen_puz)  %>% rename( endlistings_center_time1 = wla_end_nc1, endlistings_center_time2 = wla_end_nc2, endlistings_center_all = wla_end_pcz, endlistings_regional = wla_end_prz, endlistings_usa = wla_end_puz) %>% rename(deteriorated_center_time1 = wla_remdet_nc1, deteriorated_center_time2 = wla_remdet_nc2, deteriorated_center_all = wla_remdet_pcz, deteriorated_regional = wla_remdet_prz, deteriorated_usa = wla_remdet_puz) %>% rename( died_center_time1 = wla_remdied_nc1, died_center_time2 = wla_remdied_nc2, died_center_all = wla_remdied_pcz, died_regional = wla_remdied_prz, died_usa = wla_remdied_puz) %>% rename(other_center_time1 = wla_remoth_nc1, other_center_time2 = wla_remoth_nc2, other_center_all = wla_remoth_pcz, other_regional = wla_remoth_prz, other_usa = wla_remoth_puz) %>% rename( recovered_center_time1 = wla_remrec_nc1, recovered_center_time2 = wla_remrec_nc2, recovered_center_all = wla_remrec_pcz, recovered_regional = wla_remrec_prz, recovered_usa = wla_remrec_puz) %>% rename(transfer_center_time1 = wla_remtfer_nc1, transfer_center_time2 = wla_remtfer_nc2, transfer_center_all = wla_remtfer_pcz, transfer_regional = wla_remtfer_prz, transfer_usa = wla_remtfer_puz) %>% rename(deceased_donor_center_time1 = wla_remtxc_nc1, deceased_donor_center_time2 = wla_remtxc_nc2, deceased_donor_center_all = wla_remtxc_pcz, deceased_donor_regional = wla_remtxc_prz, deceased_donor_usa = wla_remtxc_puz) %>% rename(living_donor_center_time1 = wla_remtxl_nc1, living_donor_center_time2 = wla_remtxl_nc2, living_donor_center_all = wla_remtxl_pcz, living_donor_regional = wla_remtxl_prz, living_donor_usa = wla_remtxl_puz) %>% rename(transplant_other_center_time1 = wla_remtxoc_nc1, transplant_other_center_time2 = wla_remtxoc_nc2, transplant_other_center_all = wla_remtxoc_pcz, transplant_other_regional = wla_remtxoc_prz, transplant_other_center_usa = wla_remtxoc_puz) %>% rename(start_waitlist_center_time1 = wla_st_nc1, start_waitlist_center_time2 = wla_st_nc2, start_waitlist_center_all = wla_st_pcz, start_waitlist_regional = wla_st_prz, start_waitlist_usa = wla_st_puz)
  
x = x [-c(1), ]
x[, c(4,6:60)] <- sapply(x[, c(4,6:60)], as.numeric)
x = drop_na(x)
str(x)
return (x)
}
```
Outcomes and zipcodes
```{r}
outcomes_and_zipcodes = function(x){
  x = x %>% mutate(newlistings_percent_mortality = 100*died_center_all/newlistings_center_all, newlistings_percent_deteriorated = 100*deteriorated_center_all/newlistings_center_all, newlistings_percent_transfer = 100* transfer_center_all/newlistings_center_all, newlistings_percent_living_donor = 100* living_donor_center_all/newlistings_center_all, newlistings_percent_deceased_donor = 100*deceased_donor_center_all/newlistings_center_all, newlistings_percent_recovered = 100* recovered_center_all/newlistings_center_all, living_deceased_graft_ratio = living_donor_center_all/deceased_donor_center_all)
  
df_zipcodes = read_excel("../data/zipcodes.xlsx")
df_zipcodes = df_zipcodes[-c(1), ]
df_zipcodes[, c(2)] = sapply(df_zipcodes[, c(2)], as.numeric)
df_zipcodes = janitor::clean_names(df_zipcodes)

for (zipcode in df_zipcodes["zipcode"]){
    df_zip_geo = tibble(geocode_zip(zipcode))
}
df_geo_merge = merge(df_zipcodes, df_zip_geo, all = TRUE)
x = merge(x, df_geo_merge, all = TRUE)
return(x)
}
```
Exposures One
```{r}
plot_exposures_one = function(x){
  x1 = x[, c(6:20)]
ggplot(gather(x1), aes(value)) + geom_histogram(bins = 100) + facet_wrap(~key, scales = "free_y")  +coord_cartesian(xlim = c(0, 2000)) + labs(title = "Exposure Frequency Part1", subtitle = phrase, x = "Exposure (Percent)", y = "Frequency") + theme_minimal()
}
```
Exposures Part Two
```{r}
plot_exposures_two = function(x){
  x2 = x[, c(21:35)]
ggplot(gather(x2), aes(value)) + geom_histogram(bins = 100) + facet_wrap(~key, scales = "free_y") +coord_cartesian(xlim = c(0, 100)) + labs(title = "Exposure Frequency Part2", subtitle = phrase, x = "Exposure (Percent)", y = "Frequency") + theme_minimal()
}
```
Exposures Part Three
```{r}
plot_exposures_three = function(x){
x3 = x[, c(36:43)]
ggplot(gather(x3), aes(value)) + geom_histogram(bins = 100) + facet_wrap(~key, scales = "free_y") +coord_cartesian(xlim = c(0, 500)) + labs(title = "Exposure Frequency Part3", subtitle = phrase, x = "Exposure (Percent)", y = "Frequency") + theme_minimal()
}
```
Exposures Part Four
```{r}
plot_exposures_four = function(x){
x4 = x[, c(44:51)]
ggplot(gather(x4), aes(value)) + geom_histogram(bins = 100) + facet_wrap(~key, scales = "free_y") +coord_cartesian(xlim = c(0, 200)) + labs(title = "Exposure Frequency Part4", subtitle = phrase, x = "Exposure (Percent)", y = "Frequency") + theme_minimal()
}
```

Exposures Part Five
```{r}
plot_exposures_five = function(x){
x5 = x[, c(52:60)]
ggplot(gather(x5), aes(value)) + geom_histogram(bins = 100) + facet_wrap(~key, scales = "free_y") +coord_cartesian(xlim = c(0, 2000)) + labs(title = "Exposure Frequency Part5", subtitle = phrase, x = "Exposure (Percent)", y = "Frequency") + theme_minimal()
}
```

Outcomes and zipcodes
```{r}
plot_outcomes = function(x){
  x = x[, c(61:66)] %>% filter(newlistings_percent_transfer <= 100)
ggplot(gather(x), aes(value)) + geom_histogram(bins = 30) + facet_wrap(~key, scales = "free_y") + coord_cartesian(xlim = c(0, 100)) + labs(title = "Outcome Frequency", subtitle = phrase, x = "Outcome (Percent)", y = "Frequency") + theme_minimal()
}
```
Zipcode Histogram and Leaflet
```{r}
zipcode_histogram = function(x){
z = x %>% ggplot(aes(zipcode)) + geom_histogram(bins = 50) + 
  labs(
    title = "Transplant Center Frequency by Zipcode", subtitle = phrase,
    x = "Zipcode",
    y = "Transplant Center Count"
  ) + theme_minimal()
z
}
```
Leaflet
```{r, eval=FALSE}
leaflet = function(x){
library(leaflet)
leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18))
m = x %>% leaflet() %>% addTiles() %>% addCircleMarkers(lat = ~lat, lng = ~lng)
m

}
```
Master function
```{r}
automate_eda = function(x){
df_one = read_file(x)
df_one = clean_data_frame(df_one)
###make a function to plot all exposure variables
df_one = outcomes_and_zipcodes(df_one)
plot_outcomes(df_one)
zipcode_histogram(df_one)
#leaflet(df_one)
}
```



Test the functions
```{r}
df_one = read_file(path)
df_one = clean_data_frame(df_one)
df_one = outcomes_and_zipcodes(df_one)
#write a save dataframe function
plot_exposures_one(df_one)
plot_exposures_two(df_one)
plot_exposures_three(df_one)
plot_exposures_four(df_one)
plot_exposures_five(df_one)
plot_outcomes(df_one)
zipcode_histogram(df_one)
#leaflet(df_one)
```
Test master  function
```{r}
automate_eda(path)
```