---
title: "Team Meeting Notes"
date: "10/27/2021"
output: github_document
---

## Agenda Items
* Brainstorm research questions and potential datasets
* Identify team workflow and organization of resources
* Set goals, member tasks, and timeline for first deliverable
* Discuss git branching

### Potential Topics
* Kidney Transplant Center Comparison

### Potential Data Sources for Kidney Transplant Project

Current and historical data available.

1. https://www.srtr.org/transplant-centers/ny-presbyterian-hospitalcolumbia-univ-medical-center-nycp/?organ=kidney&recipientType=adult  
2. https://www.srtr.org/reports/program-specific-reports/ 
3. https://onlinelibrary.wiley.com/doi/10.1111/j.1600-6143.2008.02178.x

### Research Questions

* How do centers vary by geography -- offer acceptance ratios, who gets added/death while on waitlist, association btwn willingness to accept high-risk pts (e.g., based on kidney donor risk index, donor creatinine, hep C status) and time to transplant?
* Have centers changed their practices over time? pre-/post-COVID? seasonality? 2012-2014 vs 2015-2017 (big change in kidney allocation; change in other patterns)
* Combine with site zip code and merge with American Community Survey to evaluate differences based on demographics across sites
* Examine based on DSA; assess donation trajectory if not accepted within a given area (DSA, some radius to higher level i.e., region or larger catchment area)
* What center-related features are associated with higher/riskier offer acceptance ratios?
* graft survival, patient survival, 1-year, 3-year
* number of for profit dialysis centers around transplant centers, access less likely for pts seen at for-profit dialysis centers

### First Deliverable

**Team registration and proposal**

First, you will define your teams and propose a project. This proposal should be a **half-page to a page in length** and include:

* The group members (names and UNIs) - Done
* The tentative project title - Easy
* The motivation for this project - Kristen 
* The intended final products - Easy?   
  - website with dashboard
* The anticipated data sources - see above
* The planned analyses / visualizations / coding challenges - all   
  - Descriptive statistics   
  - by site, by time, ...   
  - Tables and plots based on questions   
  - Chloropleth maps   
  - what kind of plots?   
* The planned timeline - Harry
  
### Final Project Deadlines

* November 7 by 1:00 pm	Form a team and submit a proposal	Written proposal document
* November 10-13	Project review meeting	Zoom meeting – no “deliverable”
* December 5 by 4:00 pm	Report	Written report giving detailed project description
* December 5 by 4:00 pm	Webpage and screencast	Webpage overview of project, with short explanatory video (published online)
* December 5 by 8:00 pm	Peer assessment	Brief assessment of your teammates contributions (as a short document)
* December 10	“In class” discussion of projects	Enjoy hearing about projects! (Also get hex stickers…)

There should be one proposal per group, written collaboratively using .Rmd (rendering to a GH document) in a dedicated GitHub repo. Conceptually, this is intended to review a project that is 10% complete.

### To do
* All team members to edit [Google Doc for proposal](https://docs.google.com/document/d/1GPay1f_uq9Cp08fZPiQxeAjYNhL9D7ojNZE5lsB0K-Q/edit?usp=sharing) 
  - We will store final product as an Rmd/md file in repo 
* Harry to prepare a ppt and ref doc on branching for team
  - If anyone makes a change to the github repo, they will use branching
* Team to further brainstorm questions based on pursuing kidney transplant project
* Team to isolate specific research questions and analyses
* Team to review potential variables to answer questions, incorporate into analyses

