---
title: "Team Meeting Notes"
date: "10/20/2021"
output: github_document
---

## Agenda Items
* Brainstorm research questions and potential datasets
* Identify team workflow and organization of resources
* Set goals, member tasks, and timeline for first deliverable
* Discuss git branching

### Potential Topics
* COVID Clinical Trials
* Characterization and Temporal Analysis of Use of Travel Nurses 
* Kidney Transplant Center Comparison

### Potential Data Sources for Kidney Transplant Project

Current and historical data available.

1. https://www.srtr.org/transplant-centers/ny-presbyterian-hospitalcolumbia-univ-medical-center-nycp/?organ=kidney&recipientType=adult  
2. https://www.srtr.org/reports/program-specific-reports/  

### Research Questions

* How do centers vary by geography -- offer acceptance ratios, who gets added/death while on waitlist, association btwn willingness to accept high-risk pts (e.g., based on kidney donor risk index, donor creatinine, hep C status) and time to transplant?
* Have centers changed their practices over time?
* What center-related features are associated with higher/riskier offer acceptance ratios?

### First Deliverable

**Team registration and proposal**
First, you will define your teams and propose a project. This proposal should be a **half-page to a page in length** and include:

* The group members (names and UNIs)
* The tentative project title
* The motivation for this project
* The intended final products
* The anticipated data sources
* The planned analyses / visualizations / coding challenges
* The planned timeline

There should be one proposal per group, written collaboratively using .Rmd (rendering to a GH document) in a dedicated GitHub repo. Conceptually, this is intended to review a project that is 10% complete.

### To do

* Team to brainstorm questions based on pursuing kidney transplant projects
* If anyone makes a change to the github repo, they will use branching
