---
title: "Summary Plots"
date: "11/26/2021"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
library(ggplot2)
library(zipcodeR)
library(ggmap)
library(leaflet)
library(kableExtra)
```

Here we import datasets for age, gender, race, and blood type using a for loop, string manipulation with regular expressions, and map-reduce approach.

```{r}
phrase = "SRTR Multiorgan Transplant Data, August 2020 Release"

suffix = list("age","gender","demographics","blood_type")

for (i in suffix){
  data_path = "./data/"   # path to the data
  files = dir(data_path, 
              pattern = paste0("csrs_final_tables_2006_[A-Z][A-Z]_", i,".csv"))
  assign(paste0("df_all_", i),
         files %>%
           map(~ read_csv(file.path(data_path, .))%>%
                 mutate(org = str_replace(org, "HR", "Heart"),
                        org = str_replace(org, "HL", "Heart-Lung"),
                        org = str_replace(org, "IN", "Intestine"),
                        org = str_replace(org, "KI", "Kidney"),
                        org = str_replace(org, "KP", "Kidney-Pancreas"),
                        org = str_replace(org, "LI", "Liver"),
                        org = str_replace(org, "LU", "Lung"),
                        org = str_replace(org, "PA", "Pancreas"))) %>%
           reduce(rbind))
  }
```

Here we plot the age dataframes.
```{r}
plot = 
  df_all_age %>% 
  ggplot(aes(x = zipcode, y = age_category_percent, color = age_category)) + 
  geom_point() + 
  labs(
    title = "Patient Age Groups by Zipcode", 
    subtitle = phrase,
    x = "Zipcode",
    y = "Age Group (Percent)",
    color = "Age Group"
    ) + 
  theme_minimal() + 
  theme(axis.text.x=element_text(angle=90,hjust=1)) + 
  scale_color_hue(labels = c("Less Than 2 Years", "2 to 11 Years", 
                             "12 to 17 Years", "18 to 34 Years", 
                             "35 to 49 Years", "50 to 64 Years", 
                             "65 to 69 Years", "More Than 70 Years")) + 
  facet_wrap(~org)

plot
```

Here we plot the gender dataframes.
```{r}
plot = 
  df_all_gender %>% 
  ggplot(aes(x=zipcode, y =gender_category_percent, color = gender_category)) + 
  geom_point()+ 
  labs(title = "Patient Gender by Zipcode", 
       subtitle = phrase,
       x = "Zipcode",
       y = "Gender (Percent)", color = "Gender"
  ) + 
  theme_minimal() + 
  theme(axis.text.x=element_text(angle=90,hjust=1)) + 
  scale_color_hue(labels = c("Female", "Male")) + 
  facet_wrap(~org)

plot
```

Here we plot the race dataframes.
```{r}
plot = 
  df_all_demographics %>% 
  ggplot(aes(x=zipcode, y =race_category_percent, color = race_category)) + 
  geom_point() + 
  theme_minimal() + 
  labs(
    title = "Patient Demographics by Zipcode", subtitle = phrase,
    x = "Zipcode",
    y = "Race (Percent)", 
    color = "Race") + 
  scale_color_hue(labels = c("African American", "Asian", "Hispanic or Latino", 
                             "Other", "Unknown", "White")) + 
  theme(axis.text.x=element_text(angle=90,hjust=1)) + 
  facet_wrap(~org)

plot
```

Here we plot the blood type dataframes.
```{r}
plot = 
  df_all_blood_type %>%
  ggplot(aes(x = zipcode, y = blood_type_category_percent, color = blood_type_category)) + 
  geom_point() + 
  labs(
    title = "Patient Blood Types by Zipcode", subtitle = "SRTR Kidney Transplant Data, August 2020 Release",
    x = "Zipcode",
    y = "Blood Type (Percent)", color = "Blood Type"
  ) + 
  theme_minimal() + 
  scale_color_hue(labels = c("A", "AB", "B", "O", "Unknown")) + 
  theme(axis.text.x=element_text(angle=90, hjust=1)) + 
  facet_wrap(~org)

plot

# png('blood_type_summary.png')
```
